title
loop monitor
Monitor->Scorumd: /get_account_history(account, -1)
Scorumd->Monitor: one most recent transaction
Monitor->Scorumd: /get_account_history(account, diff)
Scorumd->Monitor: transactions processed within 10 seconds
Monitor->Monitor: filter only Trasfer operations
Monitor->Monitor: update deposit accounts
Monitor->Monitor: sleep 10 seconds
end